### ISSUE TITLE
Source field should be different for two different cards by the same provider

### ISSUE THREAD

**Issue by mukundvarma** [velicanu/expenses#10]
Right now, source appears as amex for both Amex Platinum and Amex Blue Cash. It would be better if these two appeared separately

**Comment by velicanu** [comment]
That's a good point 🤔 

One approach we could take is to keep track of the original filename for each record, in addition to the current source.

So the extractor would output something like this:
```
{
  ...,
  "source_file": "amex-filename.csv"
}
```

And source file would be preserved to the end.

**Comment by velicanu** [comment]
Closed by #21
