### ISSUE TITLE
add support for uber (barclays) visa credit card 

### ISSUE THREAD

**Issue by mukundvarma** [velicanu/expenses#9]

**Comment by velicanu** [comment]
After #23 , this should be just a matter of editing the two jsons, `card_definitions.json` and `category_definitions.json` for this card.

I'm also starting to think of how we want to enable users to add their own custom cards, I think we're moving in that direction with the recent changes.

**Comment by velicanu** [comment]
Closing this since our barclays card works on the latest branch through plaid.
